server:
  port: 857

spring:
  application:
    name: tcc-bank1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bank1?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10

# Hmily配置...
org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 30
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: db
      started: true
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hmily?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: 1234


management:
  endpoints:
    web:
      exposure:
        include: '*'